---

- name: packages pinning
  template: >
    src=pinning.j2
    dest=/etc/apt/preferences.d/ruby
  sudo: yes

- name: repositories key
  apt_key: >
    url=http://deb.bearstech.com/bearstech-archive.gpg
    state=present
  sudo: yes

- name: repositories
  apt_repository: >
    repo="{{ item }}"
    state=present
    update_cache=yes
  with_items:
    - "{{ elao_ruby_deb_url }}"
  sudo: yes

- name: packages
  apt: >
    name={{ item }}
    state=latest
  with_items:
    - ruby
  sudo: yes
